{% set name = "protis" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/{{ name }}/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: d3f17b259eab525f4e8186e173fc3dea79f9ef7cacef6b63e16ab8a6a8a0461a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.9
    - nannos >=2.6.2
    - scikit-image

test:
  imports:
    - protis
  source_files:
    - test/conda_test.py
  commands:
    - pytest -s -vv ./test/conda_test.py
  requires:
    - pytest


about:
  home: https://gitlab.com/protis/protis
  summary: Plane Wave Expansion method for photonic crystals
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - benvial
